table dc_inventory_position_current
	lineageTag: 6e01fb51-1261-4586-97ec-01c0f7b73a13
	sourceLineageTag: [gold].[dc_inventory_position_current]

	/// Distribution center units currently on hand.
	measure 'DC Units on Hand' = SUM('dc_inventory_position_current'[On Hand])
		formatString: #,0
		displayFolder: Inventory\Distribution Center
		lineageTag: 01a1a1c6-0001-0001-0001-000000000001

	/// Distinct products held in distribution centers.
	measure 'DC SKU Count' = DISTINCTCOUNT('dc_inventory_position_current'[Product ID])
		formatString: #,0
		displayFolder: Inventory\Distribution Center
		lineageTag: c1070001-0000-0000-0000-000000000001

	/// Average distribution center units per SKU.
	measure 'Avg DC Units per SKU' = DIVIDE([DC Units on Hand], [DC SKU Count], 0)
		formatString: #,0.0
		displayFolder: Inventory\Distribution Center
		lineageTag: c1070001-0000-0000-0000-000000000002

	column 'DC ID'
		dataType: int64
		formatString: 0
		lineageTag: 847804d1-5b60-4232-a3c8-4daa440a4ceb
		sourceLineageTag: dc_id
		summarizeBy: sum
		sourceColumn: dc_id

		changedProperty = Name

		annotation SummarizationSetBy = Automatic

	column 'Product ID'
		dataType: int64
		formatString: 0
		lineageTag: 637a2bb9-88bd-4b52-a68d-f453131dd46e
		sourceLineageTag: product_id
		summarizeBy: sum
		sourceColumn: product_id

		changedProperty = Name

		annotation SummarizationSetBy = Automatic

	column 'On Hand'
		dataType: int64
		formatString: 0
		lineageTag: 59670602-e36f-4c3f-ac16-f953603778a2
		sourceLineageTag: on_hand
		summarizeBy: sum
		sourceColumn: on_hand

		changedProperty = Name

		annotation SummarizationSetBy = Automatic

	partition dc_inventory_position_current = entity
		mode: directLake
		source
			entityName: dc_inventory_position_current
			schemaName: gold
			expressionSource: 'DirectLake - retail_lakehouse'

