table dim_products
	lineageTag: 7a341aa1-e4de-4e62-8737-d78ecfeea40b
	sourceLineageTag: [silver].[dim_products]

	measure '# of Products' = COUNTROWS(dim_products)
		formatString: #,0
		lineageTag: 01a1a1b1-0001-0001-0001-000000000001

	measure 'Average Product Cost' = AVERAGE(dim_products[Cost])
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: 01a1a1b1-0001-0001-0001-000000000002

	measure 'Average Product Price' = AVERAGE(dim_products[Sale Price])
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: 01a1a1b1-0001-0001-0001-000000000003

	column ID
		dataType: int64
		isHidden
		isKey
		formatString: 0
		lineageTag: 17774bf2-e801-4191-847e-316fbf614c6e
		sourceLineageTag: ID
		summarizeBy: none
		sourceColumn: ID

		annotation SummarizationSetBy = Automatic

	column 'Product Name'
		dataType: string
		lineageTag: cb4130e7-5394-4782-acf3-ab5644c978e8
		sourceLineageTag: ProductName
		summarizeBy: none
		sourceColumn: ProductName

		changedProperty = Name

		annotation SummarizationSetBy = Automatic

	column Brand
		dataType: string
		lineageTag: 1645f5d1-5281-4c6a-9573-a2041c1791db
		sourceLineageTag: Brand
		summarizeBy: none
		sourceColumn: Brand

		annotation SummarizationSetBy = Automatic

	column Company
		dataType: string
		lineageTag: df67fdcf-b472-46af-96a0-6593be141862
		sourceLineageTag: Company
		summarizeBy: none
		sourceColumn: Company

		annotation SummarizationSetBy = Automatic

	column Department
		dataType: string
		lineageTag: c148feb2-7c16-4b26-a049-ac70b86fc464
		sourceLineageTag: Department
		summarizeBy: none
		sourceColumn: Department

		annotation SummarizationSetBy = Automatic

	column Category
		dataType: string
		lineageTag: 479051c6-eb86-48bf-b815-6ea203276add
		sourceLineageTag: Category
		summarizeBy: none
		sourceColumn: Category

		annotation SummarizationSetBy = Automatic

	column Subcategory
		dataType: string
		lineageTag: 228249f7-3e8e-4fb5-888d-5b7dce073f7e
		sourceLineageTag: Subcategory
		summarizeBy: none
		sourceColumn: Subcategory

		annotation SummarizationSetBy = Automatic

	column Cost
		dataType: double
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: 7513ae09-61e6-41d4-b2b5-28905fd2b2df
		sourceLineageTag: Cost
		summarizeBy: sum
		sourceColumn: Cost

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column MSRP
		dataType: double
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: 2f861f86-9d75-4f97-b3fc-fe163069cdbc
		sourceLineageTag: MSRP
		summarizeBy: sum
		sourceColumn: MSRP

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Sale Price'
		dataType: double
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: c24767c6-4fea-47f9-9065-cfb0bff80eae
		sourceLineageTag: SalePrice
		summarizeBy: sum
		sourceColumn: SalePrice

		changedProperty = Name

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Requires Refrigeration'
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: dd0cf621-be7f-44c8-b63e-462cfadd4b68
		sourceLineageTag: RequiresRefrigeration
		summarizeBy: none
		sourceColumn: RequiresRefrigeration

		changedProperty = Name

		annotation SummarizationSetBy = Automatic

	column Taxability
		dataType: string
		lineageTag: 4496d2dc-3d8f-4844-9e61-57c6fd4c4bd5
		sourceLineageTag: taxability
		summarizeBy: none
		sourceColumn: taxability

		changedProperty = Name

		annotation SummarizationSetBy = Automatic

	column Tags
		dataType: string
		lineageTag: 4e4723a9-99e8-4ec3-b68b-e56865aa98ec
		sourceLineageTag: Tags
		summarizeBy: none
		sourceColumn: Tags

		annotation SummarizationSetBy = Automatic

	hierarchy 'Product Hierarchy'
		lineageTag: c2020001-0000-0000-0000-000000000001

		level Department
			lineageTag: c2020001-0000-0000-0000-000000000002
			column: Department

		level Category
			lineageTag: c2020001-0000-0000-0000-000000000003
			column: Category

		level Subcategory
			lineageTag: c2020001-0000-0000-0000-000000000004
			column: Subcategory

		level Product
			lineageTag: c2020001-0000-0000-0000-000000000005
			column: 'Product Name'

	hierarchy 'Brand Hierarchy'
		lineageTag: c2020001-0000-0000-0000-000000000006

		level Company
			lineageTag: c2020001-0000-0000-0000-000000000007
			column: Company

		level Brand
			lineageTag: c2020001-0000-0000-0000-000000000008
			column: Brand

		level Product
			lineageTag: c2020001-0000-0000-0000-000000000009
			column: 'Product Name'

	partition dim_products = entity
		mode: directLake
		source
			entityName: dim_products
			schemaName: silver
			expressionSource: 'DirectLake - retail_lakehouse'

