table dim_distribution_centers
	lineageTag: ae706b9b-d53f-48e5-8f09-4c969f0d6b4a
	sourceLineageTag: [silver].[dim_distribution_centers]

	measure '# of Distribution Centers' = COUNTROWS('dim_distribution_centers')
		formatString: #,0
		lineageTag: 01a1a1b4-0001-0001-0001-000000000001

	column ID
		dataType: int64
		isHidden
		isKey
		formatString: 0
		lineageTag: 3afba350-57be-485b-a77f-7f375ca85abd
		sourceLineageTag: ID
		summarizeBy: none
		sourceColumn: ID

		annotation SummarizationSetBy = Automatic

	column 'DC Number'
		dataType: string
		lineageTag: 44b8d211-1e3a-4e3e-bd7b-db2bc8964e77
		sourceLineageTag: DCNumber
		summarizeBy: none
		sourceColumn: DCNumber

		changedProperty = Name

		annotation SummarizationSetBy = Automatic

	column Address
		dataType: string
		lineageTag: efc18eac-da79-4b56-a520-1e03eab253bb
		sourceLineageTag: Address
		summarizeBy: none
		sourceColumn: Address

		annotation SummarizationSetBy = Automatic

	column 'Geography ID'
		dataType: int64
		formatString: 0
		lineageTag: 4881f71c-36d7-4f39-968c-453678861c69
		sourceLineageTag: GeographyID
		summarizeBy: count
		sourceColumn: GeographyID

		changedProperty = Name

		annotation SummarizationSetBy = Automatic

	hierarchy 'Distribution Center Hierarchy'
		lineageTag: c2050001-0000-0000-0000-000000000001

		level 'DC Number'
			lineageTag: c2050001-0000-0000-0000-000000000002
			column: 'DC Number'

	partition dim_distribution_centers = entity
		mode: directLake
		source
			entityName: dim_distribution_centers
			schemaName: silver
			expressionSource: 'DirectLake - retail_lakehouse'

