table fact_promo_lines
	lineageTag: 6f0a86e5-8a4e-44c1-a568-13af0862f5ef
	sourceLineageTag: [silver].[fact_promo_lines]

	/// Quantity of units associated with promotion line events.
	measure 'Promo Line Quantity' = SUM('fact_promo_lines'[Quantity])
		formatString: #,0
		displayFolder: Promotions\Lines
		lineageTag: a9f8319e-9d48-47b4-a119-000000000001

	/// Promotion line discount amount from discount cents.
	measure 'Promo Line Discount Amount' = DIVIDE(SUM('fact_promo_lines'[Discount Cents]), 100, 0)
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		displayFolder: Promotions\Lines
		lineageTag: a9f8319e-9d48-47b4-a119-000000000002

	column 'Receipt ID'
		dataType: string
		lineageTag: c6de1bfc-e7ba-4aef-834f-01871476eeb4
		sourceLineageTag: ReceiptId
		summarizeBy: none
		sourceColumn: ReceiptId

		changedProperty = Name

		annotation SummarizationSetBy = Automatic

	column 'Promo Code'
		dataType: string
		lineageTag: f9fe94ee-173b-47de-bf0c-a4c66636e228
		sourceLineageTag: PromoCode
		summarizeBy: none
		sourceColumn: PromoCode

		changedProperty = Name

		annotation SummarizationSetBy = Automatic

	column 'Line Number'
		dataType: int64
		formatString: 0
		lineageTag: b5260d33-03fb-4167-ab57-3ad94caf561b
		sourceLineageTag: LineNumber
		summarizeBy: sum
		sourceColumn: LineNumber

		changedProperty = Name

		annotation SummarizationSetBy = Automatic

	column 'Product ID'
		dataType: int64
		formatString: 0
		lineageTag: 191a3e31-47de-41fa-8c7e-cdfbf9505ccf
		sourceLineageTag: ProductID
		summarizeBy: count
		sourceColumn: ProductID

		changedProperty = Name

		annotation SummarizationSetBy = Automatic

	column Quantity
		dataType: int64
		formatString: 0
		lineageTag: 281f75bf-5ba8-46a7-a33e-0cfa5adf8fbc
		sourceLineageTag: Qty
		summarizeBy: sum
		sourceColumn: Qty

		changedProperty = Name

		annotation SummarizationSetBy = Automatic

	column 'Discount Amount'
		dataType: string
		lineageTag: e2dd10cf-48f9-4972-bb14-dfa8cbdf89ac
		sourceLineageTag: DiscountAmount
		summarizeBy: none
		sourceColumn: DiscountAmount

		changedProperty = Name

		annotation SummarizationSetBy = Automatic

	column 'Discount Cents'
		dataType: int64
		formatString: 0
		lineageTag: f3d66be0-70a2-4008-b5bb-7a5151b15e50
		sourceLineageTag: DiscountCents
		summarizeBy: sum
		sourceColumn: DiscountCents

		changedProperty = Name

		annotation SummarizationSetBy = Automatic

	column __index_level_0__
		dataType: int64
		formatString: 0
		lineageTag: 046e12d9-a984-4b67-81bd-5c6afeca49f4
		sourceLineageTag: __index_level_0__
		summarizeBy: sum
		sourceColumn: __index_level_0__

		annotation SummarizationSetBy = Automatic

	partition fact_promo_lines = entity
		mode: directLake
		source
			entityName: fact_promo_lines
			schemaName: silver
			expressionSource: 'DirectLake - retail_lakehouse'

