table fact_payments
	lineageTag: a9ee5779-cb04-439d-8691-5ae9eb849b4e
	sourceLineageTag: [silver].[fact_payments]

	/// Total payment amount, stored in cents and reported in currency.
	measure 'Total Amounts' = DIVIDE(SUM('fact_payments'[Amount Cents]), 100, 0)
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		displayFolder: Payments
		lineageTag: 79b75b7a-6c45-4df5-a579-ead43dd9e267

	/// Count of payment transactions.
	measure 'Payment Count' = COUNTROWS('fact_payments')
		formatString: #,0
		displayFolder: Payments
		lineageTag: c1050001-0000-0000-0000-000000000001

	/// Count of approved payment transactions.
	measure 'Approved Payment Count' = CALCULATE([Payment Count], 'fact_payments'[Status] = "APPROVED")
		formatString: #,0
		displayFolder: Payments
		lineageTag: c1050001-0000-0000-0000-000000000002

	/// Count of declined payment transactions.
	measure 'Declined Payment Count' = CALCULATE([Payment Count], 'fact_payments'[Status] = "DECLINED")
		formatString: #,0
		displayFolder: Payments
		lineageTag: c1050001-0000-0000-0000-000000000003

	/// Declined payment transactions as a percentage of all payment transactions.
	measure 'Payment Decline Rate %' = DIVIDE([Declined Payment Count], [Payment Count], 0)
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: Payments
		lineageTag: c1050001-0000-0000-0000-000000000004

	/// Average payment processing latency in milliseconds.
	measure 'Avg Payment Processing MS' = AVERAGE('fact_payments'[Processing Time MS])
		formatString: #,0.0
		displayFolder: Payments
		lineageTag: c1050001-0000-0000-0000-000000000005

	column 'Receipt ID'
		dataType: string
		lineageTag: efbefad1-5a1b-4c7b-925f-848b4de594d5
		sourceLineageTag: receipt_id_ext
		summarizeBy: none
		sourceColumn: receipt_id_ext

		changedProperty = Name

		annotation SummarizationSetBy = Automatic

	column 'Order ID'
		dataType: string
		lineageTag: 52dc2ac3-3b91-401d-acea-49838020c2fe
		sourceLineageTag: order_id_ext
		summarizeBy: none
		sourceColumn: order_id_ext

		changedProperty = Name

		annotation SummarizationSetBy = Automatic

	column 'Payment Method'
		dataType: string
		lineageTag: 325aa4a0-21a6-4c72-918d-7d9872000f8c
		sourceLineageTag: payment_method
		summarizeBy: none
		sourceColumn: payment_method

		changedProperty = Name

		annotation SummarizationSetBy = Automatic

	column 'Amount Cents'
		dataType: int64
		formatString: 0
		lineageTag: 72a5cd30-df81-4cea-8a0c-857458089bba
		sourceLineageTag: amount_cents
		summarizeBy: sum
		sourceColumn: amount_cents

		changedProperty = Name

		annotation SummarizationSetBy = Automatic

	column Amount
		dataType: string
		lineageTag: f0c241fa-f5f0-4ab3-b743-15761fcd487b
		sourceLineageTag: amount
		summarizeBy: none
		sourceColumn: amount

		changedProperty = Name

		annotation SummarizationSetBy = Automatic

	column 'Transaction ID'
		dataType: string
		lineageTag: 59a3a364-edd0-4bed-870d-3dafc0dfdd1a
		sourceLineageTag: transaction_id
		summarizeBy: none
		sourceColumn: transaction_id

		changedProperty = Name

		annotation SummarizationSetBy = Automatic

	column 'Processing Time MS'
		dataType: int64
		formatString: 0
		lineageTag: 1e22bae8-128a-41d4-bca5-d5f14abcdc70
		sourceLineageTag: processing_time_ms
		summarizeBy: sum
		sourceColumn: processing_time_ms

		changedProperty = Name

		annotation SummarizationSetBy = Automatic

	column Status
		dataType: string
		lineageTag: 3544e80a-5367-46e2-a81d-55965f62ec8b
		sourceLineageTag: status
		summarizeBy: none
		sourceColumn: status

		changedProperty = Name

		annotation SummarizationSetBy = Automatic

	column 'Decline Reason'
		dataType: string
		lineageTag: 52669962-9147-40a0-a3e5-1a1df7faac53
		sourceLineageTag: decline_reason
		summarizeBy: none
		sourceColumn: decline_reason

		changedProperty = Name

		annotation SummarizationSetBy = Automatic

	column 'Store ID'
		dataType: int64
		formatString: 0
		lineageTag: d21b659a-0979-44b0-ad34-53109ed5050d
		sourceLineageTag: store_id
		summarizeBy: sum
		sourceColumn: store_id

		changedProperty = Name

		annotation SummarizationSetBy = Automatic

	column 'Customer ID'
		dataType: int64
		formatString: 0
		lineageTag: ae5fe31f-a97a-4799-93fb-98b992cf414d
		sourceLineageTag: customer_id
		summarizeBy: sum
		sourceColumn: customer_id

		changedProperty = Name

		annotation SummarizationSetBy = Automatic

	column 'Event Timestamp'
		dataType: dateTime
		formatString: General Date
		lineageTag: a1a1a1a3-0000-0000-0000-000000000010
		sourceLineageTag: event_ts
		summarizeBy: none
		sourceColumn: event_ts

		annotation SummarizationSetBy = Automatic

	column event_date
		dataType: dateTime
		formatString: General Date
		lineageTag: 2bb53d73-00fd-47c4-bedd-668c3f5f5eec
		sourceLineageTag: event_date
		summarizeBy: none
		sourceColumn: event_date

		annotation SummarizationSetBy = Automatic

	partition fact_payments = entity
		mode: directLake
		source
			entityName: fact_payments
			schemaName: silver
			expressionSource: 'DirectLake - retail_lakehouse'

