table fact_truck_moves
	lineageTag: 486b3beb-5e42-4766-b0d7-1147520e5a37
	sourceLineageTag: [silver].[fact_truck_moves]

	/// Count of truck movement events.
	measure 'Truck Move Count' = COUNTROWS('fact_truck_moves')
		formatString: #,0
		displayFolder: Logistics\Truck Moves
		lineageTag: a9f8319e-9d48-47b4-a120-000000000001

	/// Average actual unload duration from truck move events.
	measure 'Avg Unload Duration' = AVERAGE('fact_truck_moves'[actual_unload_duration])
		formatString: #,0.0
		displayFolder: Logistics\Truck Moves
		lineageTag: a9f8319e-9d48-47b4-a120-000000000002

	column Status
		dataType: string
		lineageTag: 05d465cc-c274-4016-80ec-bd258e36f80c
		sourceLineageTag: status
		summarizeBy: none
		sourceColumn: status

		changedProperty = Name

		annotation SummarizationSetBy = Automatic

	column 'Shipment ID'
		dataType: string
		lineageTag: 18d1a5ed-9272-4f3e-a6fb-3a01cbd4a295
		sourceLineageTag: shipment_id
		summarizeBy: none
		sourceColumn: shipment_id

		changedProperty = Name

		annotation SummarizationSetBy = Automatic

	column 'DC ID'
		dataType: int64
		formatString: 0
		lineageTag: 8cc6a6be-bcbb-4e57-a42e-383babd8c30c
		sourceLineageTag: dc_id
		summarizeBy: sum
		sourceColumn: dc_id

		changedProperty = Name

		annotation SummarizationSetBy = Automatic

	column 'Truck ID'
		dataType: int64
		formatString: 0
		lineageTag: f91cf596-0f96-4834-b402-c55cbabbad71
		sourceLineageTag: truck_id
		summarizeBy: sum
		sourceColumn: truck_id

		changedProperty = Name

		annotation SummarizationSetBy = Automatic

	column 'Store ID'
		dataType: int64
		formatString: 0
		lineageTag: 54d28e85-f677-4d6c-a288-e1e48f68932e
		sourceLineageTag: store_id
		summarizeBy: sum
		sourceColumn: store_id

		changedProperty = Name

		annotation SummarizationSetBy = Automatic

	column actual_unload_duration
		dataType: double
		lineageTag: 8f57805e-ee66-4e80-bb3f-832c006ec88c
		sourceLineageTag: actual_unload_duration
		summarizeBy: sum
		sourceColumn: actual_unload_duration

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column __index_level_0__
		dataType: int64
		formatString: 0
		lineageTag: 442f04c0-247c-4c09-abe5-459a292e17ad
		sourceLineageTag: __index_level_0__
		summarizeBy: sum
		sourceColumn: __index_level_0__

		annotation SummarizationSetBy = Automatic

	partition fact_truck_moves = entity
		mode: directLake
		source
			entityName: fact_truck_moves
			schemaName: silver
			expressionSource: 'DirectLake - retail_lakehouse'

