table fact_store_inventory_txn
	lineageTag: 069e006d-82a8-46ab-abf7-39d781c37887
	sourceLineageTag: [silver].[fact_store_inventory_txn]

	measure 'Total Inventory Transactions' = COUNTROWS('fact_store_inventory_txn')
		formatString: #,0
		lineageTag: 0842b7d4-e5fc-4a12-9064-a9332276a9e1

	measure 'Total Quantity Delta' = SUM('fact_store_inventory_txn'[Quantity])
		formatString: #,0
		lineageTag: 01a1a1a6-0001-0001-0001-000000000002

	column 'Transaction Type'
		dataType: string
		lineageTag: fcdbfd4d-1ec4-422f-b7bd-a6a83e8b03c9
		sourceLineageTag: txn_type
		summarizeBy: none
		sourceColumn: txn_type

		changedProperty = Name

		annotation SummarizationSetBy = Automatic

	column Quantity
		dataType: int64
		formatString: 0
		lineageTag: b4460922-757f-4b4e-8fbc-5c30dd6b3740
		sourceLineageTag: quantity
		summarizeBy: sum
		sourceColumn: quantity

		changedProperty = Name

		annotation SummarizationSetBy = Automatic

	column Balance
		dataType: int64
		formatString: 0
		lineageTag: 34eee0a6-d403-445d-83a6-163c9c0da520
		sourceLineageTag: balance
		summarizeBy: sum
		sourceColumn: balance

		changedProperty = Name

		annotation SummarizationSetBy = Automatic

	column 'Product ID'
		dataType: int64
		formatString: 0
		lineageTag: 85ecab4a-5ef0-4c6a-bcbd-2db04af2a261
		sourceLineageTag: product_id
		summarizeBy: sum
		sourceColumn: product_id

		changedProperty = Name

		annotation SummarizationSetBy = Automatic

	column 'Store ID'
		dataType: int64
		formatString: 0
		lineageTag: f9411773-fe61-4cc9-bd55-1a200d71cdf8
		sourceLineageTag: store_id
		summarizeBy: sum
		sourceColumn: store_id

		changedProperty = Name

		annotation SummarizationSetBy = Automatic

	column Source
		dataType: string
		lineageTag: 4f1e13af-0613-492f-9b82-4b2c53340348
		sourceLineageTag: source
		summarizeBy: none
		sourceColumn: source

		changedProperty = Name

		annotation SummarizationSetBy = Automatic

	column __index_level_0__
		dataType: int64
		formatString: 0
		lineageTag: 8ec48b5d-e930-43ca-900a-3ffce43b7a6f
		sourceLineageTag: __index_level_0__
		summarizeBy: sum
		sourceColumn: __index_level_0__

		annotation SummarizationSetBy = Automatic

	partition fact_store_inventory_txn = entity
		mode: directLake
		source
			entityName: fact_store_inventory_txn
			schemaName: silver
			expressionSource: 'DirectLake - retail_lakehouse'

