table fact_receipts
	lineageTag: dbb3a597-d860-42d1-9585-a7da0fc2a2a4
	sourceLineageTag: [silver].[fact_receipts]

	/// Total store sales from receipt headers, stored in cents and reported in currency.
	measure 'Total Sales' = DIVIDE(SUM('fact_receipts'[Total Cents]), 100, 0)
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		displayFolder: Core Metrics\Sales
		lineageTag: 01a1a1a1-0001-0001-0001-000000000001

	/// Total tax collected from store receipts.
	measure 'Total Tax' = DIVIDE(SUM('fact_receipts'[Tax Cents]), 100, 0)
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		displayFolder: Core Metrics\Sales
		lineageTag: 01a1a1a1-0001-0001-0001-000000000002

	/// Store receipt subtotal before tax.
	measure 'Total Subtotal' = DIVIDE(SUM('fact_receipts'[Subtotal Cents]), 100, 0)
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		displayFolder: Core Metrics\Sales
		lineageTag: 01a1a1a1-0001-0001-0001-000000000003

	/// Count of store receipts.
	measure 'Receipt Count' = COUNTROWS('fact_receipts')
		formatString: #,0
		displayFolder: Core Metrics\Sales
		lineageTag: 01a1a1a1-0001-0001-0001-000000000004

	/// Average store receipt value.
	measure 'Average Basket Size' = DIVIDE([Total Sales], [Receipt Count], 0)
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		displayFolder: Core Metrics\Sales
		lineageTag: 01a1a1a1-0001-0001-0001-000000000005

	/// Sales associated with return receipts.
	measure 'Total Returns' = CALCULATE([Total Sales], 'fact_receipts'[Receipt Type] = "RETURN")
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		displayFolder: Core Metrics\Returns
		lineageTag: 01a1a1a1-0001-0001-0001-000000000006

	/// Net store sales (line-level). Sources from fact_receipt_lines so product/department/category filters propagate correctly.
	measure 'Net Sales' = [Line Revenue]
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		displayFolder: Core Metrics\Sales
		lineageTag: 01a1a1a1-0001-0001-0001-000000000007

	/// Month-to-date net store sales.
	measure 'Store Sales MTD' = CALCULATE([Net Sales], DATESMTD('dim_date'[Date]))
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		displayFolder: Time Intelligence\Store Sales
		lineageTag: c1010001-0000-0000-0000-000000000001

	/// Quarter-to-date net store sales.
	measure 'Store Sales QTD' = CALCULATE([Net Sales], DATESQTD('dim_date'[Date]))
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		displayFolder: Time Intelligence\Store Sales
		lineageTag: c1010001-0000-0000-0000-000000000002

	/// Year-to-date net store sales.
	measure 'Store Sales YTD' = CALCULATE([Net Sales], DATESYTD('dim_date'[Date]))
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		displayFolder: Time Intelligence\Store Sales
		lineageTag: c1010001-0000-0000-0000-000000000003

	/// Prior-year net store sales for the selected period.
	measure 'Store Sales PY' = CALCULATE([Net Sales], SAMEPERIODLASTYEAR('dim_date'[Date]))
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		displayFolder: Time Intelligence\Store Sales
		lineageTag: c1010001-0000-0000-0000-000000000004

	/// Year-over-year store sales growth percentage.
	measure 'Store Sales YoY %' = VAR CurrentSales = [Net Sales] VAR PriorSales = [Store Sales PY] RETURN DIVIDE(CurrentSales - PriorSales, PriorSales, BLANK())
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: Time Intelligence\Store Sales
		lineageTag: c1010001-0000-0000-0000-000000000005

	/// Year-to-date count of store receipts.
	measure 'Receipt Count YTD' = CALCULATE([Receipt Count], DATESYTD('dim_date'[Date]))
		formatString: #,0
		displayFolder: Time Intelligence\Store Sales
		lineageTag: c1010001-0000-0000-0000-000000000006

	/// Store sales normalized by active stores in the filter context.
	measure 'Sales per Store' = DIVIDE([Net Sales], [# of Stores], 0)
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		displayFolder: Core Metrics\Productivity
		lineageTag: c1010001-0000-0000-0000-000000000007

	/// Store sales normalized by active customers in the filter context.
	measure 'Sales per Customer' = DIVIDE([Net Sales], [# of Customers], 0)
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		displayFolder: Core Metrics\Productivity
		lineageTag: c1010001-0000-0000-0000-000000000008

	/// Return sales as a percentage of total store sales.
	measure 'Return Rate %' = DIVIDE(ABS([Total Returns]), [Total Sales], 0)
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: Core Metrics\Returns
		lineageTag: c1010001-0000-0000-0000-000000000009

	/// Combined store and online revenue (line-level on both sides so product filters propagate to the decomp tree).
	measure 'Omnichannel Revenue' = [Net Sales] + [Online Line Revenue]
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		displayFolder: Omnichannel
		lineageTag: c1010001-0000-0000-0000-00000000000a

	/// Combined store receipts and online orders.
	measure 'Omnichannel Orders' = [Receipt Count] + [Online Order Count]
		formatString: #,0
		displayFolder: Omnichannel
		lineageTag: c1010001-0000-0000-0000-00000000000b

	/// Average value across store receipts and online orders.
	measure 'Omnichannel AOV' = DIVIDE([Omnichannel Revenue], [Omnichannel Orders], 0)
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		displayFolder: Omnichannel
		lineageTag: c1010001-0000-0000-0000-00000000000c

	/// Store sales share of combined omnichannel revenue.
	measure 'Store Sales % of Omnichannel' = DIVIDE([Net Sales], [Omnichannel Revenue], 0)
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: Omnichannel
		lineageTag: c1010001-0000-0000-0000-00000000000d

	/// Online sales share of combined omnichannel revenue (line-level for consistency with Omnichannel Revenue).
	measure 'Online Sales % of Omnichannel' = DIVIDE([Online Line Revenue], [Omnichannel Revenue], 0)
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: Omnichannel
		lineageTag: c1010001-0000-0000-0000-00000000000e

	/// Year-to-date omnichannel revenue.
	measure 'Omnichannel Revenue YTD' = CALCULATE([Omnichannel Revenue], DATESYTD('dim_date'[Date]))
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		displayFolder: Time Intelligence\Omnichannel
		lineageTag: c1010001-0000-0000-0000-00000000000f

	/// Prior-year omnichannel revenue for the selected period.
	measure 'Omnichannel Revenue PY' = CALCULATE([Omnichannel Revenue], SAMEPERIODLASTYEAR('dim_date'[Date]))
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		displayFolder: Time Intelligence\Omnichannel
		lineageTag: c1010001-0000-0000-0000-000000000010

	/// Year-over-year omnichannel revenue growth percentage.
	measure 'Omnichannel Revenue YoY %' = VAR CurrentRevenue = [Omnichannel Revenue] VAR PriorRevenue = [Omnichannel Revenue PY] RETURN DIVIDE(CurrentRevenue - PriorRevenue, PriorRevenue, BLANK())
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: Time Intelligence\Omnichannel
		lineageTag: c1010001-0000-0000-0000-000000000011

	/// Net store sales for the previous month in the current filter context.
	measure 'Store Sales PM' = CALCULATE([Net Sales], DATEADD('dim_date'[Date], -1, MONTH))
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		displayFolder: Time Intelligence\Store Sales
		lineageTag: c1010001-0000-0000-0000-00000000001a

	/// Month-over-month net store sales growth percentage.
	measure 'Store Sales MoM %' = VAR Curr = [Net Sales] VAR Prev = [Store Sales PM] RETURN DIVIDE(Curr - Prev, Prev, BLANK())
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: Time Intelligence\Store Sales
		lineageTag: c1010001-0000-0000-0000-00000000001b

	/// Net store sales for the previous quarter in the current filter context.
	measure 'Store Sales PQ' = CALCULATE([Net Sales], DATEADD('dim_date'[Date], -1, QUARTER))
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		displayFolder: Time Intelligence\Store Sales
		lineageTag: c1010001-0000-0000-0000-00000000001c

	/// Quarter-over-quarter net store sales growth percentage.
	measure 'Store Sales QoQ %' = VAR Curr = [Net Sales] VAR Prev = [Store Sales PQ] RETURN DIVIDE(Curr - Prev, Prev, BLANK())
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: Time Intelligence\Store Sales
		lineageTag: c1010001-0000-0000-0000-00000000001d

	/// Net store sales for the prior day in the current filter context.
	measure 'Store Sales PD' = CALCULATE([Net Sales], DATEADD('dim_date'[Date], -1, DAY))
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		displayFolder: Time Intelligence\Store Sales
		lineageTag: c1010001-0000-0000-0000-00000000001e

	/// Day-over-day net store sales growth percentage.
	measure 'Store Sales DoD %' = VAR Curr = [Net Sales] VAR Prev = [Store Sales PD] RETURN DIVIDE(Curr - Prev, Prev, BLANK())
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: Time Intelligence\Store Sales
		lineageTag: c1010001-0000-0000-0000-00000000001f

	/// Trailing 7-day net store sales.
	measure 'Store Sales 7D' = CALCULATE([Net Sales], DATESINPERIOD('dim_date'[Date], MAX('dim_date'[Date]), -7, DAY))
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		displayFolder: Time Intelligence\Store Sales
		lineageTag: c1010001-0000-0000-0000-000000000020

	/// Net store sales for the prior 7-day window (8-14 days ago).
	measure 'Store Sales 7D PW' = CALCULATE([Net Sales], DATESINPERIOD('dim_date'[Date], MAX('dim_date'[Date]) - 7, -7, DAY))
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		displayFolder: Time Intelligence\Store Sales
		lineageTag: c1010001-0000-0000-0000-000000000021

	/// Week-over-week net store sales growth percentage.
	measure 'Store Sales WoW %' = VAR Curr = [Store Sales 7D] VAR Prev = [Store Sales 7D PW] RETURN DIVIDE(Curr - Prev, Prev, BLANK())
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: Time Intelligence\Store Sales
		lineageTag: c1010001-0000-0000-0000-000000000022

	/// Most recent calendar year with receipt data (hidden helper). Globally scoped so it is invariant to slicers.
	measure '_Latest Sales Year' = YEAR(CALCULATE(MAX('fact_receipts'[Event Timestamp]), REMOVEFILTERS('dim_date')))
		formatString: 0
		isHidden
		displayFolder: Time Intelligence\Latest Year
		lineageTag: c1010001-0000-0000-0000-000000000030

	/// Net Sales scoped to the latest year of receipt data, preserving any month bucket on the visual axis. Use on TY/PY trend visuals.
	measure 'Net Sales (Latest Year)' = VAR Yr = [_Latest Sales Year] RETURN CALCULATE([Net Sales], REMOVEFILTERS('dim_date'[Year]), REMOVEFILTERS('dim_date'[Date]), 'dim_date'[Year] = Yr)
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		displayFolder: Time Intelligence\Latest Year
		lineageTag: c1010001-0000-0000-0000-000000000031

	/// Net Sales scoped to the year before the latest year of receipt data. Use as the PY series on TY/PY trend visuals.
	measure 'Net Sales (Prior Year)' = VAR Yr = [_Latest Sales Year] RETURN CALCULATE([Net Sales], REMOVEFILTERS('dim_date'[Year]), REMOVEFILTERS('dim_date'[Date]), 'dim_date'[Year] = Yr - 1)
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		displayFolder: Time Intelligence\Latest Year
		lineageTag: c1010001-0000-0000-0000-000000000032

	/// Omnichannel Revenue scoped to the latest year of receipt data, preserving any month bucket on the visual axis.
	measure 'Omnichannel Revenue (Latest Year)' = VAR Yr = [_Latest Sales Year] RETURN CALCULATE([Omnichannel Revenue], REMOVEFILTERS('dim_date'[Year]), REMOVEFILTERS('dim_date'[Date]), 'dim_date'[Year] = Yr)
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		displayFolder: Time Intelligence\Latest Year
		lineageTag: c1010001-0000-0000-0000-000000000033

	/// Omnichannel Revenue scoped to the year before the latest year of receipt data.
	measure 'Omnichannel Revenue (Prior Year)' = VAR Yr = [_Latest Sales Year] RETURN CALCULATE([Omnichannel Revenue], REMOVEFILTERS('dim_date'[Year]), REMOVEFILTERS('dim_date'[Date]), 'dim_date'[Year] = Yr - 1)
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		displayFolder: Time Intelligence\Latest Year
		lineageTag: c1010001-0000-0000-0000-000000000034

	column 'Customer ID'
		dataType: int64
		formatString: 0
		lineageTag: 3c038d61-f1c4-4c76-b595-e823714c2eb0
		sourceLineageTag: customer_id
		summarizeBy: none
		sourceColumn: customer_id

		changedProperty = Name

		annotation SummarizationSetBy = Automatic

	column 'Discount Amount'
		dataType: string
		lineageTag: d8fdc9a6-23b4-4899-adb4-bfe4d04448eb
		sourceLineageTag: discount_amount
		summarizeBy: none
		sourceColumn: discount_amount

		changedProperty = Name

		annotation SummarizationSetBy = Automatic

	column 'Subtotal Cents'
		dataType: int64
		formatString: 0
		lineageTag: d10cc217-8d54-4f48-9786-c2788f401552
		sourceLineageTag: subtotal_cents
		summarizeBy: sum
		sourceColumn: subtotal_cents

		changedProperty = Name

		annotation SummarizationSetBy = Automatic

	column 'Receipt Type'
		dataType: string
		lineageTag: f8a25262-9dde-476e-b2f1-94341f833092
		sourceLineageTag: receipt_type
		summarizeBy: none
		sourceColumn: receipt_type

		changedProperty = Name

		annotation SummarizationSetBy = Automatic

	column 'Payment Method'
		dataType: string
		lineageTag: feff8b81-9380-4f52-8965-e1c810debcc0
		sourceLineageTag: payment_method
		summarizeBy: none
		sourceColumn: payment_method

		changedProperty = Name

		annotation SummarizationSetBy = Automatic

	column 'Receipt ID'
		dataType: string
		isHidden
		isKey
		lineageTag: 63ca03aa-3389-4a3c-a601-c8fbf8359291
		sourceLineageTag: receipt_id_ext
		summarizeBy: none
		sourceColumn: receipt_id_ext

		changedProperty = Name

		annotation SummarizationSetBy = Automatic

	column 'Total Amount'
		dataType: string
		lineageTag: 74c4603e-8ab4-487a-8d69-19de12151b9a
		sourceLineageTag: total_amount
		summarizeBy: none
		sourceColumn: total_amount

		changedProperty = Name

		annotation SummarizationSetBy = Automatic

	column 'Total Cents'
		dataType: int64
		formatString: 0
		lineageTag: 648ce335-e019-4757-b4bc-e88c0e005ef7
		sourceLineageTag: total_cents
		summarizeBy: sum
		sourceColumn: total_cents

		changedProperty = Name

		annotation SummarizationSetBy = Automatic

	column 'Tax Amount'
		dataType: string
		lineageTag: c4521791-db0f-4658-bb3f-9ca3197a12b7
		sourceLineageTag: tax_amount
		summarizeBy: none
		sourceColumn: tax_amount

		changedProperty = Name

		annotation SummarizationSetBy = Automatic

	column 'Store ID'
		dataType: int64
		formatString: 0
		lineageTag: aa658e70-f275-4c6d-91c8-63d908c09403
		sourceLineageTag: store_id
		summarizeBy: sum
		sourceColumn: store_id

		changedProperty = Name

		annotation SummarizationSetBy = Automatic

	column 'Tax Cents'
		dataType: int64
		formatString: 0
		lineageTag: c4715f0e-a9e5-4470-ac33-ec16b9f046c2
		sourceLineageTag: tax_cents
		summarizeBy: sum
		sourceColumn: tax_cents

		changedProperty = Name

		annotation SummarizationSetBy = Automatic

	column Subtotal
		dataType: string
		lineageTag: da77bc23-568e-4c61-ad68-49d35f133cd0
		sourceLineageTag: Subtotal
		summarizeBy: none
		sourceColumn: Subtotal

		annotation SummarizationSetBy = Automatic

	column 'Event Timestamp'
		dataType: dateTime
		formatString: General Date
		lineageTag: a1a1a1a1-0000-0000-0000-000000000010
		sourceLineageTag: event_ts
		summarizeBy: none
		sourceColumn: event_ts

		annotation SummarizationSetBy = Automatic

	/// Date portion of the receipt event timestamp. Used for the dim_date relationship (Direct Lake requires matching column types, so this date column relates to dim_date[Date] instead of the timestamp).
	column 'Event Date'
		dataType: dateTime
		formatString: Short Date
		lineageTag: a1a1a1a1-0000-0000-0000-000000000011
		sourceLineageTag: event_date
		summarizeBy: none
		sourceColumn: event_date

		annotation SummarizationSetBy = Automatic

	partition fact_receipts = entity
		mode: directLake
		source
			entityName: fact_receipts
			schemaName: silver
			expressionSource: 'DirectLake - retail_lakehouse'

