table fact_foot_traffic
	lineageTag: c999b61a-43db-4db3-9783-626a4618f864
	sourceLineageTag: [silver].[fact_foot_traffic]

	/// Total observed in-store foot traffic count.
	measure 'Foot Traffic Count' = SUM('fact_foot_traffic'[Count])
		formatString: #,0
		displayFolder: Store Operations\Traffic
		lineageTag: 01a1a1cb-0001-0001-0001-000000000001

	/// Average dwell minutes per observed in-store visitor.
	measure 'Avg Foot Traffic Dwell Minutes' = DIVIDE(SUM('fact_foot_traffic'[Dwell Seconds]), [Foot Traffic Count] * 60, 0)
		formatString: #,0.0
		displayFolder: Store Operations\Traffic
		lineageTag: 01a1a1cb-0001-0001-0001-000000000002

	/// Store receipt conversion proxy from receipts divided by observed traffic.
	measure 'Traffic Conversion Proxy %' = DIVIDE([Receipt Count], [Foot Traffic Count], 0)
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: Store Operations\Traffic
		lineageTag: c1140001-0000-0000-0000-000000000001

	column Count
		dataType: int64
		formatString: 0
		lineageTag: 13698da9-5865-4083-92e8-31aa304ddb63
		sourceLineageTag: count
		summarizeBy: sum
		sourceColumn: count

		changedProperty = Name

		annotation SummarizationSetBy = Automatic

	column Zone
		dataType: string
		lineageTag: 557ac75c-0e4d-4954-981c-67823bfdd6e0
		sourceLineageTag: zone
		summarizeBy: none
		sourceColumn: zone

		changedProperty = Name

		annotation SummarizationSetBy = Automatic

	column 'Dwell Seconds'
		dataType: int64
		formatString: 0
		lineageTag: f6e707b1-08c4-41fa-ab1a-233ec061d176
		sourceLineageTag: dwell_seconds
		summarizeBy: sum
		sourceColumn: dwell_seconds

		changedProperty = Name

		annotation SummarizationSetBy = Automatic

	column 'Store ID'
		dataType: int64
		formatString: 0
		lineageTag: 569af1b5-d33d-496c-b590-76158423c9ce
		sourceLineageTag: store_id
		summarizeBy: sum
		sourceColumn: store_id

		changedProperty = Name

		annotation SummarizationSetBy = Automatic

	column 'Sensor ID'
		dataType: string
		lineageTag: 347e7b41-cd79-4e79-8f79-45413192743c
		sourceLineageTag: sensor_id
		summarizeBy: none
		sourceColumn: sensor_id

		changedProperty = Name

		annotation SummarizationSetBy = Automatic

	/// Date portion of the foot traffic event timestamp. Used for the dim_date relationship (Direct Lake requires matching column types).
	column 'Event Date'
		dataType: dateTime
		formatString: Short Date
		lineageTag: 347e7b41-cd79-4e79-8f79-45413192743d
		sourceLineageTag: event_date
		summarizeBy: none
		sourceColumn: event_date

		annotation SummarizationSetBy = Automatic

	partition fact_foot_traffic = entity
		mode: directLake
		source
			entityName: fact_foot_traffic
			schemaName: silver
			expressionSource: 'DirectLake - retail_lakehouse'

