table fact_online_order_lines
	lineageTag: ead55580-9419-45ac-91ff-f5ac29096866
	sourceLineageTag: [silver].[fact_online_order_lines]

	/// Total online item units.
	measure 'Total Online Units' = SUM('fact_online_order_lines'[Quantity])
		formatString: #,0
		displayFolder: Core Metrics\Online
		lineageTag: 01a1a1a4-0001-0001-0001-000000000001

	/// Online order line revenue, stored in cents and reported in currency.
	measure 'Online Line Revenue' = DIVIDE(SUM('fact_online_order_lines'[Extended Cents]), 100, 0)
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		displayFolder: Core Metrics\Online
		lineageTag: 01a1a1a4-0001-0001-0001-000000000002

	/// Average online order-line unit price.
	measure 'Average Online Unit Price' = DIVIDE([Online Line Revenue], [Total Online Units], 0)
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		displayFolder: Core Metrics\Online
		lineageTag: 01a1a1a4-0001-0001-0001-000000000003

	/// Total store plus online item units.
	measure 'Omnichannel Units' = [Total Units Sold] + [Total Online Units]
		formatString: #,0
		displayFolder: Omnichannel
		lineageTag: c1040001-0000-0000-0000-000000000001

	/// Online units share of combined item units.
	measure 'Online Units % of Omnichannel' = DIVIDE([Total Online Units], [Omnichannel Units], 0)
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: Omnichannel
		lineageTag: c1040001-0000-0000-0000-000000000002

	/// Average online units per online order.
	measure 'Online Units per Order' = DIVIDE([Total Online Units], [Online Order Count], 0)
		formatString: #,0.00
		displayFolder: Core Metrics\Online
		lineageTag: c1040001-0000-0000-0000-000000000003

	column 'Order ID'
		dataType: string
		lineageTag: 8ed9dac6-9c06-4081-9067-1862bb870d3c
		sourceLineageTag: order_id
		summarizeBy: none
		sourceColumn: order_id

		changedProperty = Name

		annotation SummarizationSetBy = Automatic

	column 'Unit Cents'
		dataType: int64
		formatString: 0
		lineageTag: b71747a4-7708-49b7-ac7a-e81e89e23573
		sourceLineageTag: unit_cents
		summarizeBy: sum
		sourceColumn: unit_cents

		changedProperty = Name

		annotation SummarizationSetBy = Automatic

	column 'Fulfillment Mode'
		dataType: string
		lineageTag: bf44a73e-258e-48d2-92a9-9df7f0037725
		sourceLineageTag: fulfillment_mode
		summarizeBy: none
		sourceColumn: fulfillment_mode

		changedProperty = Name

		annotation SummarizationSetBy = Automatic

	column 'Promo Code'
		dataType: string
		lineageTag: 0710082e-09b1-4ed6-9298-a29be7298c5d
		sourceLineageTag: promo_code
		summarizeBy: none
		sourceColumn: promo_code

		changedProperty = Name

		annotation SummarizationSetBy = Automatic

	column 'Node Type'
		dataType: string
		lineageTag: d0806b14-a539-49aa-ad23-8ae789dd08b6
		sourceLineageTag: node_type
		summarizeBy: none
		sourceColumn: node_type

		changedProperty = Name

		annotation SummarizationSetBy = Automatic

	column 'Product ID'
		dataType: int64
		formatString: 0
		lineageTag: 7a040420-92ea-4167-a7e8-35029e01d4dd
		sourceLineageTag: product_id
		summarizeBy: sum
		sourceColumn: product_id

		changedProperty = Name

		annotation SummarizationSetBy = Automatic

	column 'Extended Price'
		dataType: string
		lineageTag: 2083d296-c3fa-4e6c-bcb1-a974818b7265
		sourceLineageTag: ext_price
		summarizeBy: none
		sourceColumn: ext_price

		changedProperty = Name

		annotation SummarizationSetBy = Automatic

	column 'Extended Cents'
		dataType: int64
		formatString: 0
		lineageTag: 5004ecb4-e6e2-4ec7-b12a-30cb9cc7a7a3
		sourceLineageTag: ext_cents
		summarizeBy: sum
		sourceColumn: ext_cents

		changedProperty = Name

		annotation SummarizationSetBy = Automatic

	column 'Line Number'
		dataType: int64
		formatString: 0
		lineageTag: 6d4df010-8f4e-4a12-aae4-d74075cb4dd8
		sourceLineageTag: line_num
		summarizeBy: sum
		sourceColumn: line_num

		changedProperty = Name

		annotation SummarizationSetBy = Automatic

	column 'Fulfillment Status'
		dataType: string
		lineageTag: 520daddd-488d-4ea5-b0f3-0bf808a6d8b7
		sourceLineageTag: fulfillment_status
		summarizeBy: none
		sourceColumn: fulfillment_status

		changedProperty = Name

		annotation SummarizationSetBy = Automatic

	column 'Unit Price'
		dataType: string
		lineageTag: ba2c5305-e11e-45b5-bc3e-4bdaf6e4b350
		sourceLineageTag: unit_price
		summarizeBy: none
		sourceColumn: unit_price

		changedProperty = Name

		annotation SummarizationSetBy = Automatic

	column Quantity
		dataType: int64
		formatString: 0
		lineageTag: 61bc9749-947f-4815-bc67-3f0a61c0b032
		sourceLineageTag: quantity
		summarizeBy: sum
		sourceColumn: quantity

		changedProperty = Name

		annotation SummarizationSetBy = Automatic

	column 'Node ID'
		dataType: int64
		formatString: 0
		lineageTag: 46f9dba7-f1fe-421f-b5d6-5753941c2834
		sourceLineageTag: node_id
		summarizeBy: sum
		sourceColumn: node_id

		changedProperty = Name

		annotation SummarizationSetBy = Automatic

	column __index_level_0__
		dataType: int64
		formatString: 0
		lineageTag: cf8ce641-935d-42f3-abb6-40101e6c746e
		sourceLineageTag: __index_level_0__
		summarizeBy: sum
		sourceColumn: __index_level_0__

		annotation SummarizationSetBy = Automatic

	partition fact_online_order_lines = entity
		mode: directLake
		source
			entityName: fact_online_order_lines
			schemaName: silver
			expressionSource: 'DirectLake - retail_lakehouse'

