table fact_online_order_headers
	lineageTag: 930ea7c8-e0a4-4f4a-a7df-1cf98fbeeefd
	sourceLineageTag: [silver].[fact_online_order_headers]

	/// Total online order sales, stored in cents and reported in currency.
	measure 'Total Online Sales' = DIVIDE(SUM('fact_online_order_headers'[Total Cents]), 100, 0)
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		displayFolder: Core Metrics\Online
		lineageTag: 01a1a1a3-0001-0001-0001-000000000001

	/// Total online order tax.
	measure 'Total Online Tax' = DIVIDE(SUM('fact_online_order_headers'[Tax Cents]), 100, 0)
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		displayFolder: Core Metrics\Online
		lineageTag: 01a1a1a3-0001-0001-0001-000000000002

	/// Online order subtotal before tax.
	measure 'Total Online Subtotal' = DIVIDE(SUM('fact_online_order_headers'[Subtotal Cents]), 100, 0)
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		displayFolder: Core Metrics\Online
		lineageTag: 01a1a1a3-0001-0001-0001-000000000003

	/// Count of online order headers.
	measure 'Online Order Count' = COUNTROWS('fact_online_order_headers')
		formatString: #,0
		displayFolder: Core Metrics\Online
		lineageTag: 01a1a1a3-0001-0001-0001-000000000004

	/// Average online order value.
	measure 'Average Online Order Value' = DIVIDE([Total Online Sales], [Online Order Count], 0)
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		displayFolder: Core Metrics\Online
		lineageTag: 01a1a1a3-0001-0001-0001-000000000005

	/// Year-to-date online sales.
	measure 'Online Sales YTD' = CALCULATE([Total Online Sales], DATESYTD('dim_date'[Date]))
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		displayFolder: Time Intelligence\Online
		lineageTag: c1030001-0000-0000-0000-000000000001

	/// Prior-year online sales.
	measure 'Online Sales PY' = CALCULATE([Total Online Sales], SAMEPERIODLASTYEAR('dim_date'[Date]))
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		displayFolder: Time Intelligence\Online
		lineageTag: c1030001-0000-0000-0000-000000000002

	/// Year-over-year online sales growth percentage.
	measure 'Online Sales YoY %' = VAR CurrentSales = [Total Online Sales] VAR PriorSales = [Online Sales PY] RETURN DIVIDE(CurrentSales - PriorSales, PriorSales, BLANK())
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: Time Intelligence\Online
		lineageTag: c1030001-0000-0000-0000-000000000003

	column 'Customer ID'
		dataType: int64
		formatString: 0
		lineageTag: c6cd591e-21eb-4a48-82fe-be8ca75c1e34
		sourceLineageTag: customer_id
		summarizeBy: sum
		sourceColumn: customer_id

		changedProperty = Name

		annotation SummarizationSetBy = Automatic

	column 'Subtotal Cents'
		dataType: int64
		formatString: 0
		lineageTag: 7c45861b-0559-41b0-8f45-d366dc2fc071
		sourceLineageTag: subtotal_cents
		summarizeBy: sum
		sourceColumn: subtotal_cents

		changedProperty = Name

		annotation SummarizationSetBy = Automatic

	column 'Order ID'
		dataType: string
		isHidden
		isKey
		lineageTag: 549cb01f-8401-439b-94a1-03ce546d388c
		sourceLineageTag: order_id_ext
		summarizeBy: none
		sourceColumn: order_id_ext

		changedProperty = Name

		annotation SummarizationSetBy = Automatic

	column 'Payment Method'
		dataType: string
		lineageTag: 2c6791b3-9bd0-4cb7-8e8d-172fdbb2bde6
		sourceLineageTag: payment_method
		summarizeBy: none
		sourceColumn: payment_method

		changedProperty = Name

		annotation SummarizationSetBy = Automatic

	column 'Total Amount'
		dataType: string
		lineageTag: 41239a23-abc8-447a-ace2-d14d407e989c
		sourceLineageTag: total_amount
		summarizeBy: none
		sourceColumn: total_amount

		changedProperty = Name

		annotation SummarizationSetBy = Automatic

	column 'Total Cents'
		dataType: int64
		formatString: 0
		lineageTag: 2123d982-0ece-4589-a4cb-d2154af602cd
		sourceLineageTag: total_cents
		summarizeBy: sum
		sourceColumn: total_cents

		changedProperty = Name

		annotation SummarizationSetBy = Automatic

	column 'Tax Amount'
		dataType: string
		lineageTag: 3d73f23c-7703-4673-a845-52220518b0e5
		sourceLineageTag: tax_amount
		summarizeBy: none
		sourceColumn: tax_amount

		changedProperty = Name

		annotation SummarizationSetBy = Automatic

	column 'Subtotal Amount'
		dataType: string
		lineageTag: 18653173-4d8b-4cf3-b061-7399ace2daa0
		sourceLineageTag: subtotal_amount
		summarizeBy: none
		sourceColumn: subtotal_amount

		changedProperty = Name

		annotation SummarizationSetBy = Automatic

	column 'Tax Cents'
		dataType: int64
		formatString: 0
		lineageTag: d5a18cad-980f-4839-8303-5bfde6a48bc8
		sourceLineageTag: tax_cents
		summarizeBy: sum
		sourceColumn: tax_cents

		changedProperty = Name

		annotation SummarizationSetBy = Automatic

	/// Date portion of the order event timestamp. Used for the dim_date relationship (Direct Lake requires matching column types, so this date column relates to dim_date[Date] instead of the timestamp).
	column 'Event Date'
		dataType: dateTime
		formatString: Short Date
		lineageTag: a2a2a2a3-0000-0000-0000-000000000002
		sourceLineageTag: event_date
		summarizeBy: none
		sourceColumn: event_date

		annotation SummarizationSetBy = Automatic

	partition fact_online_order_headers = entity
		mode: directLake
		source
			entityName: fact_online_order_headers
			schemaName: silver
			expressionSource: 'DirectLake - retail_lakehouse'

