table inventory_position_current
	lineageTag: 80253872-c9ec-4d0d-b638-c3c5163306c3
	sourceLineageTag: [gold].[inventory_position_current]

	/// Store units currently on hand.
	measure 'Total Units on Hand' = SUM('inventory_position_current'[On Hand])
		formatString: #,0
		displayFolder: Inventory\Store
		lineageTag: 01a1a1a5-0001-0001-0001-000000000001

	/// Store inventory cost value using product standard cost.
	measure 'Total Inventory Value' = SUMX('inventory_position_current', VAR ProductCost = LOOKUPVALUE('dim_products'[Cost], 'dim_products'[ID], 'inventory_position_current'[Product ID]) RETURN 'inventory_position_current'[On Hand] * COALESCE(ProductCost, 0))
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		displayFolder: Inventory\Store
		lineageTag: 01a1a1a5-0001-0001-0001-000000000002

	/// Store inventory retail value using product sale price.
	measure 'Total Inventory Retail Value' = SUMX('inventory_position_current', VAR ProductSalePrice = LOOKUPVALUE('dim_products'[Sale Price], 'dim_products'[ID], 'inventory_position_current'[Product ID]) RETURN 'inventory_position_current'[On Hand] * COALESCE(ProductSalePrice, 0))
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		displayFolder: Inventory\Store
		lineageTag: 01a1a1a5-0001-0001-0001-000000000003

	/// Distinct store/product inventory positions.
	measure 'Store SKU Count' = DISTINCTCOUNT('inventory_position_current'[Product ID])
		formatString: #,0
		displayFolder: Inventory\Store
		lineageTag: c1060001-0000-0000-0000-000000000001

	/// Average on-hand units per store SKU.
	measure 'Avg Store Units per SKU' = DIVIDE([Total Units on Hand], [Store SKU Count], 0)
		formatString: #,0.0
		displayFolder: Inventory\Store
		lineageTag: c1060001-0000-0000-0000-000000000002

	/// Store inventory retail value minus cost value.
	measure 'Inventory Margin Value' = [Total Inventory Retail Value] - [Total Inventory Value]
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		displayFolder: Inventory\Margin
		lineageTag: c1060001-0000-0000-0000-000000000003

	/// Store inventory margin percentage at current retail price.
	measure 'Inventory Margin %' = DIVIDE([Inventory Margin Value], [Total Inventory Retail Value], 0)
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: Inventory\Margin
		lineageTag: c1060001-0000-0000-0000-000000000004

	/// Combined store and distribution center on-hand units.
	measure 'Network Units on Hand' = [Total Units on Hand] + [DC Units on Hand]
		formatString: #,0
		displayFolder: Inventory\Network
		lineageTag: c1060001-0000-0000-0000-000000000005

	/// Store inventory retail value compared with store sales in the current filter context.
	measure 'Inventory to Sales Ratio' = DIVIDE([Total Inventory Retail Value], [Net Sales], 0)
		formatString: #,0.00
		displayFolder: Inventory\Productivity
		lineageTag: c1060001-0000-0000-0000-000000000006

	column 'Store ID'
		dataType: int64
		formatString: 0
		lineageTag: 657f2501-30bd-49f7-b3b0-979a5491791c
		sourceLineageTag: store_id
		summarizeBy: sum
		sourceColumn: store_id

		changedProperty = Name

		annotation SummarizationSetBy = Automatic

	column 'Product ID'
		dataType: int64
		formatString: 0
		lineageTag: cbc2790a-4977-4e9b-af30-d485dcdee191
		sourceLineageTag: product_id
		summarizeBy: sum
		sourceColumn: product_id

		changedProperty = Name

		annotation SummarizationSetBy = Automatic

	column 'On Hand'
		dataType: int64
		formatString: 0
		lineageTag: 4ac72f8c-f640-45cd-9cac-8d4f713b4b58
		sourceLineageTag: on_hand
		summarizeBy: sum
		sourceColumn: on_hand

		changedProperty = Name

		annotation SummarizationSetBy = Automatic

	partition inventory_position_current = entity
		mode: directLake
		source
			entityName: inventory_position_current
			schemaName: gold
			expressionSource: 'DirectLake - retail_lakehouse'

