table online_sales_daily
	lineageTag: a2c1b744-09a3-4341-9934-282e0cd86ef7
	sourceLineageTag: [gold].[online_sales_daily]

	measure 'Online Revenue' = SUM('online_sales_daily'[Total])
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: 01a1a1c3-0001-0001-0001-000000000001

	measure 'Online Orders' = SUM('online_sales_daily'[Orders])
		formatString: #,0
		lineageTag: 01a1a1c3-0001-0001-0001-000000000002

	measure 'Online Average Order Value' = DIVIDE([Online Revenue], [Online Orders], 0)
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: 01a1a1c3-0001-0001-0001-000000000003

	column Day
		dataType: dateTime
		formatString: General Date
		lineageTag: cee9ed17-cbb5-4d0c-adcc-3409673e03cf
		sourceLineageTag: day
		summarizeBy: none
		sourceColumn: day

		changedProperty = Name

		annotation SummarizationSetBy = Automatic

	column Orders
		dataType: int64
		formatString: 0
		lineageTag: f4bcbe79-377f-4716-b883-62aa5f638594
		sourceLineageTag: orders
		summarizeBy: sum
		sourceColumn: orders

		changedProperty = Name

		annotation SummarizationSetBy = Automatic

	column Subtotal
		dataType: double
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: daa6013d-b5a8-43f0-be98-281031ed3583
		sourceLineageTag: subtotal
		summarizeBy: sum
		sourceColumn: subtotal

		changedProperty = Name

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Tax
		dataType: double
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: 9b698455-789b-499d-bbd1-62106620fb61
		sourceLineageTag: tax
		summarizeBy: sum
		sourceColumn: tax

		changedProperty = Name

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Total
		dataType: double
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: 3a046b1a-adfc-42b8-8da4-631614088a5f
		sourceLineageTag: total
		summarizeBy: sum
		sourceColumn: total

		changedProperty = Name

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Average Order Value'
		dataType: double
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: 793db82f-f43e-4840-88d5-e9395c64a96a
		sourceLineageTag: avg_order_value
		summarizeBy: sum
		sourceColumn: avg_order_value

		changedProperty = Name

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition online_sales_daily = entity
		mode: directLake
		source
			entityName: online_sales_daily
			schemaName: gold
			expressionSource: 'DirectLake - retail_lakehouse'

