table top_products_15m
	lineageTag: eda9ac0d-bc37-4363-96b4-298c279801bc
	sourceLineageTag: [gold].[top_products_15m]

	measure 'Top Product Revenue' = SUM('top_products_15m'[Revenue])
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: 01a1a1c2-0001-0001-0001-000000000001

	measure 'Top Product Units' = SUM('top_products_15m'[Units])
		formatString: #,0
		lineageTag: 01a1a1c2-0001-0001-0001-000000000002

	column 'Product ID'
		dataType: int64
		formatString: 0
		lineageTag: f71dd371-de91-495f-ad76-db7f3c6fde8b
		sourceLineageTag: product_id
		summarizeBy: sum
		sourceColumn: product_id

		changedProperty = Name

		annotation SummarizationSetBy = Automatic

	column Revenue
		dataType: double
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: 95625462-5b71-47fe-8186-915a9a4f1d6a
		sourceLineageTag: revenue
		summarizeBy: sum
		sourceColumn: revenue

		changedProperty = Name

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Units
		dataType: int64
		formatString: 0
		lineageTag: 11114f49-2e94-4a9e-9066-1d07443626fc
		sourceLineageTag: units
		summarizeBy: sum
		sourceColumn: units

		changedProperty = Name

		annotation SummarizationSetBy = Automatic

	partition top_products_15m = entity
		mode: directLake
		source
			entityName: top_products_15m
			schemaName: gold
			expressionSource: 'DirectLake - retail_lakehouse'

