table truck_dwell_daily
	lineageTag: 27b86d53-bcc1-4b0c-a6b6-bef459bc35ed
	sourceLineageTag: [gold].[truck_dwell_daily]

	/// Total truck visits in daily dwell aggregates.
	measure 'Total Trucks' = SUM('truck_dwell_daily'[Trucks])
		formatString: #,0
		displayFolder: Logistics\Dwell
		lineageTag: 01a1a1c7-0001-0001-0001-000000000001

	/// Average truck dwell minutes.
	measure 'Avg Truck Dwell Minutes' = AVERAGE('truck_dwell_daily'[Average Dwell Minutes])
		formatString: #,0.0
		displayFolder: Logistics\Dwell
		lineageTag: 01a1a1c7-0001-0001-0001-000000000002

	/// Daily site rows where average dwell exceeds 45 minutes.
	measure 'Truck Dwell Breach Days' = COUNTROWS(FILTER('truck_dwell_daily', 'truck_dwell_daily'[Average Dwell Minutes] > 45))
		formatString: #,0
		displayFolder: Logistics\Dwell
		lineageTag: c1130001-0000-0000-0000-000000000001

	/// Truck visits per active site in the filter context.
	measure 'Trucks per Site' = DIVIDE([Total Trucks], DISTINCTCOUNT('truck_dwell_daily'[Site]), 0)
		formatString: #,0.0
		displayFolder: Logistics\Dwell
		lineageTag: c1130001-0000-0000-0000-000000000002

	column Site
		dataType: string
		lineageTag: ad2e4e82-92c0-41a1-8e1a-15bbeb1093cb
		sourceLineageTag: site
		summarizeBy: none
		sourceColumn: site

		changedProperty = Name

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: dateTime
		formatString: General Date
		lineageTag: 4bd080fb-437b-41f8-83ce-beb768501d61
		sourceLineageTag: day
		summarizeBy: none
		sourceColumn: day

		changedProperty = Name

		annotation SummarizationSetBy = Automatic

	column 'Average Dwell Minutes'
		dataType: double
		lineageTag: d8e13419-3a71-47f4-baea-c166a92a46db
		sourceLineageTag: avg_dwell_min
		summarizeBy: sum
		sourceColumn: avg_dwell_min

		changedProperty = Name

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Trucks
		dataType: int64
		formatString: 0
		lineageTag: 7908b1e2-0c3c-4dc5-9250-eb7bf836fde4
		sourceLineageTag: trucks
		summarizeBy: sum
		sourceColumn: trucks

		changedProperty = Name

		annotation SummarizationSetBy = Automatic

	partition truck_dwell_daily = entity
		mode: directLake
		source
			entityName: truck_dwell_daily
			schemaName: gold
			expressionSource: 'DirectLake - retail_lakehouse'

