table zone_dwell_minute
	lineageTag: 0bf09335-5a4f-471c-9b09-32b6f8261fa6
	sourceLineageTag: [gold].[zone_dwell_minute]

	measure 'Zone Customers' = SUM('zone_dwell_minute'[Customers])
		formatString: #,0
		lineageTag: 01a1a1c8-0001-0001-0001-000000000001

	measure 'Avg Zone Dwell' = AVERAGE('zone_dwell_minute'[Average Dwell])
		formatString: #,0.0
		lineageTag: 01a1a1c8-0001-0001-0001-000000000002

	column 'Store ID'
		dataType: int64
		formatString: 0
		lineageTag: cbd46151-4680-4fd3-9a7c-0e95183412ff
		sourceLineageTag: store_id
		summarizeBy: sum
		sourceColumn: store_id

		changedProperty = Name

		annotation SummarizationSetBy = Automatic

	column Zone
		dataType: string
		lineageTag: 120f9883-3652-4a83-846c-b4d438b1a3ba
		sourceLineageTag: zone
		summarizeBy: none
		sourceColumn: zone

		changedProperty = Name

		annotation SummarizationSetBy = Automatic

	column Timestamp
		dataType: dateTime
		formatString: General Date
		lineageTag: c26e9f9a-56af-4116-96f6-089843545694
		sourceLineageTag: ts
		summarizeBy: none
		sourceColumn: ts

		changedProperty = Name

		annotation SummarizationSetBy = Automatic

	column 'Average Dwell'
		dataType: double
		lineageTag: 3e664904-d5dc-47c4-9316-6313e996935b
		sourceLineageTag: avg_dwell
		summarizeBy: sum
		sourceColumn: avg_dwell

		changedProperty = Name

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Customers
		dataType: int64
		formatString: 0
		lineageTag: 88c3825c-bbdd-4e69-8b8e-9c36eca2a746
		sourceLineageTag: customers
		summarizeBy: sum
		sourceColumn: customers

		changedProperty = Name

		annotation SummarizationSetBy = Automatic

	partition zone_dwell_minute = entity
		mode: directLake
		source
			entityName: zone_dwell_minute
			schemaName: gold
			expressionSource: 'DirectLake - retail_lakehouse'

