# %% [markdown]
# # Setup 02 — Generate dimensions
# Part of the retail-demo setup utility. Re-runnable (overwrite-by-design).
#
# Requires setup-01 (dictionaries seeded under `Files/setup/dictionaries/`).
# The engine cell below is generated by `scripts/build_notebooks.py` — edit
# the package sources under `utility/src/retail_setup/`, never the cell.

# %%
# Fabric's Spark runtime ships an OLD typing_extensions and no pydantic, while the
# inlined engine below imports pydantic. Install both on the driver, then make the
# new typing_extensions actually load. Why each step:
#  - subprocess pip (not %pip): a %pip kernel restart tears down the Spark session
#    mid pipeline run and fails the activity.
#  - pin pydantic <2.12: 2.12+ imports typing_extensions.Sentinel.
#  - drop the stale modules from sys.modules: the runtime already imported the old
#    typing_extensions, so the freshly installed copy is shadowed; evicting it lets
#    the engine cell re-import the upgraded versions (pydantic needs symbols such
#    as TypeIs that the runtime's typing_extensions lacks).
#  - pydantic runs only on the driver (engine builds rows, then
#    spark.createDataFrame), so a driver-side install is sufficient.
import importlib
import subprocess
import sys

subprocess.check_call([
    sys.executable, "-m", "pip", "install", "--quiet",
    "typing_extensions>=4.12.2", "pydantic>=2,<2.12",
])
for _name in [m for m in list(sys.modules)
              if m.split(".", 1)[0] in {"typing_extensions", "typing_inspection",
                                        "pydantic", "pydantic_core"}]:
    del sys.modules[_name]
importlib.invalidate_caches()

# %%
# PARAMETERS — rendered by `retail-setup render`; defaults work unrendered
def _param(value: str, default: str) -> str:
    return default if len(value) > 1 and value[0] == value[1] == "{" else value

LAKEHOUSE_NAME = _param("{{LAKEHOUSE_NAME}}", "retail_lakehouse")
SILVER_DB = _param("{{SILVER_DB}}", "silver")
GOLD_DB = _param("{{GOLD_DB}}", "gold")
STORE_TYPE = _param("{{STORE_TYPE}}", "supercenter")
START_DATE = _param("{{START_DATE}}", "2025-01-01")
END_DATE = _param("{{END_DATE}}", "2025-03-31")
STORE_COUNT = int(_param("{{STORE_COUNT}}", "50"))
SEED = int(_param("{{SEED}}", "42"))
DICTIONARY_REF = _param("{{DICTIONARY_REF}}", "main")

spark.conf.set("spark.sql.session.timeZone", "UTC")  # engine timestamps depend on it
# Reorder seeded-draw math ((xxhash64(...)/1e12)*k -> (xxhash64(...)*k)/1e12) to
# cut rounding-error propagation and silence Fabric's Spark advisor. The rewrite
# shifts draws by <=1 ULP (generation is statistical, no exact-value contracts);
# set in every engine driver so dims and facts stay mutually consistent.
spark.conf.set("spark.advise.divisionExprConvertRule.enable", "true")

# %% [engine]

# %% [markdown]
# ## Generate and write dimensions

# %%
from datetime import date

cfg = GenerationConfig(
    store_type=STORE_TYPE,
    start_date=date.fromisoformat(START_DATE),
    end_date=date.fromisoformat(END_DATE),
    store_count=STORE_COUNT,
    seed=SEED,
    silver_db=SILVER_DB,
    gold_db=GOLD_DB,
    dictionary_root="/lakehouse/default/Files/setup/dictionaries",
)
dicts = load_dictionaries(cfg.resolved_dictionary_root, cfg.store_type)

dims = generate_dimensions(spark, dicts, cfg)
# dim_date is padded ±5 years — the semantic model's date relationships
# need the headroom around the generated fact window.
dims["dim_date"] = generate_dim_date(
    spark, _shift_year(cfg.start_date, -5), _shift_year(cfg.end_date, 5))

spark.sql(f"CREATE DATABASE IF NOT EXISTS {LAKEHOUSE_NAME}.{SILVER_DB}")
for name, df in dims.items():
    write_to_lakehouse(df, LAKEHOUSE_NAME, SILVER_DB, name)
    # Count the written table, not df: df.count() would recompute the dimension
    # generation; the persisted Delta table answers count() from metadata.
    n = spark.table(f"{LAKEHOUSE_NAME}.{SILVER_DB}.{name}").count()
    print(f"wrote {LAKEHOUSE_NAME}.{SILVER_DB}.{name}: {n:,} rows")
